[package]
name = "stm_ethernet"
description = "Little projects using the STM32F429 Ethernet"
license = "Apache-2.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
version = "0.1.0"
repository = "https://github.com/birkenfeld/stm_ethernet"
edition = "2018"

[dependencies]
log = "0.4"
arrayvec = { version = "0.4", default-features = false }
byteorder = { version = "1.2", default-features = false }
cortex-m = "0.5"
cortex-m-rt = "0.6"
panic-itm = "0.4"
stm32f4xx-hal = { version = "0.4", features = ["rt", "stm32f429"] }
stm32-eth = { git = "https://github.com/birkenfeld/stm32-eth", features = ["smoltcp-phy", "nucleo-f429zi"] }
#stm32-eth = { path = "../stm32-eth", features = ["smoltcp-phy", "nucleo-f429zi"] }

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp"
default-features = false
features = ["proto-ipv4", "proto-dhcpv4", "socket-icmp", "socket-udp", "socket-tcp"]

[profile.release]
debug = 1
lto = true
